// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the extension/oidcclientauth component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("oidcclientauth")
	ScopeName = "github.com/vcheesbrough/otlp-collector-oidc/extension/oidcclientauth"
)

const (
	ExtensionStability = component.StabilityLevelDevelopment
)
