// Code generated by mdatagen. DO NOT EDIT.

package metadatatest

import (
	"testing"

	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/component/componenttest"
	"go.opentelemetry.io/collector/receiver"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.opentelemetry.io/otel/sdk/metric/metricdata"
	"go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest"
)

func NewSettings(tt *componenttest.Telemetry) receiver.Settings {
	set := receivertest.NewNopSettings(receivertest.NopType)
	set.ID = component.NewID(component.MustNewType("otlpsingleport"))
	set.TelemetrySettings = tt.NewTelemetrySettings()
	return set
}

func AssertEqualOtlpsingleportRequestsRefused(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	want := metricdata.Metrics{
		Name:        "otelcol_otlpsingleport_requests_refused",
		Description: "Requests refused before they reach the pipeline, by transport (grpc, http) and reason (method, media_type, body_too_large, decode, unknown_path, decompress). Refusals by the pipeline itself are receiver_refused_*. [Development]",
		Unit:        "{request}",
		Data: metricdata.Sum[int64]{
			Temporality: metricdata.CumulativeTemporality,
			IsMonotonic: true,
			DataPoints:  dps,
		},
	}
	got, err := tt.GetMetric("otelcol_otlpsingleport_requests_refused")
	require.NoError(t, err)
	metricdatatest.AssertEqual(t, want, got, opts...)
}
