// Command otlp-collector-oidc is the collector distribution's binary.
//
// components.go is generated by ocb from builder.yaml; this file replaces
// ocb's generated main so the version comes from the linker (internal/build)
// and the binary has a version subcommand. The confmap providers below are
// the ones builder.yaml lists.
package main

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/provider/envprovider"
	"go.opentelemetry.io/collector/confmap/provider/fileprovider"
	"go.opentelemetry.io/collector/confmap/provider/yamlprovider"
	"go.opentelemetry.io/collector/otelcol"

	"github.com/vcheesbrough/otlp-collector-oidc/internal/build"
)

func main() {
	info := component.BuildInfo{
		Command:     "otlp-collector-oidc",
		Description: "OpenTelemetry Collector distribution that authenticates OTLP clients with OIDC",
		Version:     build.Version(),
	}
	cmd := otelcol.NewCommand(otelcol.CollectorSettings{
		BuildInfo: info,
		Factories: components,
		ConfigProviderSettings: otelcol.ConfigProviderSettings{
			ResolverSettings: confmap.ResolverSettings{
				ProviderFactories: []confmap.ProviderFactory{
					envprovider.NewFactory(),
					fileprovider.NewFactory(),
					yamlprovider.NewFactory(),
				},
			},
		},
	})
	cmd.AddCommand(&cobra.Command{
		Use:   "version",
		Short: "Print the version and exit",
		Args:  cobra.NoArgs,
		Run: func(c *cobra.Command, _ []string) {
			fmt.Fprintln(c.OutOrStdout(), info.Version)
		},
	})
	if err := cmd.Execute(); err != nil {
		// cobra has already printed the error.
		os.Exit(1)
	}
}
