// Command otlp-collector-oidc is the collector distribution's binary.
//
// components.go is generated by ocb from builder.yaml; this file replaces
// ocb's generated main so the version comes from the linker (internal/build)
// and the binary has two subcommands of its own: run, which renders the
// configuration from the environment (internal/render) and is what the image
// runs, and version. The root command is the stock collector command, taking
// --config. The confmap providers below are the ones builder.yaml lists.
package main

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/provider/envprovider"
	"go.opentelemetry.io/collector/confmap/provider/fileprovider"
	"go.opentelemetry.io/collector/confmap/provider/yamlprovider"
	"go.opentelemetry.io/collector/otelcol"

	"github.com/vcheesbrough/otlp-collector-oidc/internal/build"
	"github.com/vcheesbrough/otlp-collector-oidc/internal/render"
)

func main() {
	set := settings()
	cmd := otelcol.NewCommand(set)
	cmd.AddCommand(render.Command(set, os.LookupEnv, os.Unsetenv, os.TempDir()))
	cmd.AddCommand(&cobra.Command{
		Use:   "version",
		Short: "Print the version and exit",
		Args:  cobra.NoArgs,
		Run: func(c *cobra.Command, _ []string) {
			fmt.Fprintln(c.OutOrStdout(), set.BuildInfo.Version)
		},
	})
	if err := cmd.Execute(); err != nil {
		// cobra has already printed the error.
		os.Exit(1)
	}
}

// settings is the collector this distribution builds, before any
// configuration is chosen.
func settings() otelcol.CollectorSettings {
	return otelcol.CollectorSettings{
		BuildInfo: component.BuildInfo{
			Command:     build.Command,
			Description: "OpenTelemetry Collector distribution that authenticates OTLP clients with OIDC",
			Version:     build.Version(),
		},
		Factories: components,
		ConfigProviderSettings: otelcol.ConfigProviderSettings{
			ResolverSettings: confmap.ResolverSettings{
				ProviderFactories: []confmap.ProviderFactory{
					envprovider.NewFactory(),
					fileprovider.NewFactory(),
					yamlprovider.NewFactory(),
				},
			},
		},
	}
}
