// Code generated by mdatagen. DO NOT EDIT.

package metadatatest

import (
	"testing"

	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/component/componenttest"
	"go.opentelemetry.io/collector/extension"
	"go.opentelemetry.io/collector/extension/extensiontest"
	"go.opentelemetry.io/otel/sdk/metric/metricdata"
	"go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest"
)

func NewSettings(tt *componenttest.Telemetry) extension.Settings {
	set := extensiontest.NewNopSettings(extensiontest.NopType)
	set.ID = component.NewID(component.MustNewType("oidcclientauth"))
	set.TelemetrySettings = tt.NewTelemetrySettings()
	return set
}

func AssertEqualOidcclientauthRejections(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	want := metricdata.Metrics{
		Name:        "otelcol_oidcclientauth_rejections",
		Description: "Requests the authenticator refused, by reason (no_token, invalid_token, missing_scope, missing_claim, not_ready). [Development]",
		Unit:        "{request}",
		Data: metricdata.Sum[int64]{
			Temporality: metricdata.CumulativeTemporality,
			IsMonotonic: true,
			DataPoints:  dps,
		},
	}
	got, err := tt.GetMetric("otelcol_oidcclientauth_rejections")
	require.NoError(t, err)
	metricdatatest.AssertEqual(t, want, got, opts...)
}
